/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuthentication } from "./IAuthentication";
export type { ISignaturesValidator } from "./ISignaturesValidator";
export type { ITemporarilyPausable } from "./ITemporarilyPausable";
