/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Flashloan__factory } from "./Flashloan__factory";
export { FlashloanV2__factory } from "./FlashloanV2__factory";
